//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel_On_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Service
    {
        public int Cls_Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public Nullable<int> Service_Id { get; set; }
        public Nullable<int> Emp_Id { get; set; }
        public Nullable<int> dept_Id { get; set; }
        public Nullable<int> Payment { get; set; }
        public Nullable<int> No_OF_Services { get; set; }
    
        public virtual Client_Registration Client_Registration { get; set; }
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Service Service { get; set; }
    }
}
