//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel_On_Services.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Contact
    {
        [Required(ErrorMessage = "First Name must be filled")]
        public string First_Name { get; set; }
        [Required(ErrorMessage = "Last Name must be filled")]
        public string Last_Name { get; set; }
        [Required(ErrorMessage = "Email must be filled")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Subject must be filled")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Message must be filled")]
        public string Message { get; set; }
    }
}
