//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel_On_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Client_Service = new HashSet<Client_Service>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int Dept_Id { get; set; }
        public string Dept_name { get; set; }
    
        public virtual ICollection<Client_Service> Client_Service { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
