//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel_On_Services.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Client_Service = new HashSet<Client_Service>();
        }
    
        public int Emp_Id { get; set; }
        public Nullable<int> dept_id { get; set; }
        [Required(ErrorMessage = "Employee Name must be filled")]
        public string Emp_Name { get; set; }
        [Required(ErrorMessage = "Email must be filled")]
        public string Emp_Email { get; set; }
        [Required(ErrorMessage = "Contact must be filled")]
        public string Emp_Contact { get; set; }
        [Required(ErrorMessage = "Address must be filled")]
        public string Emp_Address { get; set; }
        [Required(ErrorMessage = "Gender must be filled")]
        public string Emp_Gender { get; set; }
        [Required(ErrorMessage = "Salary must be filled")]
        public string Emp_Salary { get; set; }
        [Required(ErrorMessage = "Service must be filled")]
        public string Type_Of_Service { get; set; }
        [Required(ErrorMessage = "Insert your Image")]
        public string Emp_Images { get; set; }
    
        public virtual ICollection<Client_Service> Client_Service { get; set; }
        public virtual Department Department { get; set; }
    }
}
