//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel_On_Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Client_Service = new HashSet<Client_Service>();
        }
    
        public int Service_Id { get; set; }
        public string Service_Name { get; set; }
        public string Service__Description { get; set; }
        public Nullable<int> Service_Rate { get; set; }
        public string Status_Of_Payment { get; set; }
    
        public virtual ICollection<Client_Service> Client_Service { get; set; }
    }
}
